$(document).ready(function(){
    $("#research").hover(
        function(){
            $("#research").addClass("active").fadeTo("slow");       
        },
        function(){
            $("#research").fadeTo("slow").removeClass("active");
        }
     );
     $('.carousel').carousel();
});